name: Python Package using Conda

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.90
      uses: actions/setup-python@v2
      with:
        python-version: 3.90
        
    - name: Initialize Conda for Powershell
      run: |
        (Get-Command python).Path
        C:\Miniconda/condabin/conda.bat update -n base -c defaults conda
        C:\Miniconda/condabin/conda.bat init powershell
    - name: Update and Start Conda Env
      run: |
        C:\Miniconda/condabin/conda.bat env update --file environment.yml --name base
        C:\Miniconda/condabin/conda.bat activate base
   
    - name: Test with flake8 (Bug Testing)
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pylint (Style Checking)
      run: |
        conda install pylint
        pylint 
        
    - name: Run Unit tests
      run: |
        python -m unittest discover 
        
